### ISSUE TITLE
Error: java.lang.IndexOutOfBoundsException: Field index must be between 2 and 128

### ISSUE THREAD

**Issue by herusdianto** [chochos/j8583#69]
Sir I have a problem here, can you please tell me what is wrong with my config?
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE j8583-config PUBLIC "-//J8583//DTD CONFIG 1.0//EN"
    "http://j8583.sourceforge.net/j8583.dtd">
<j8583-config>

    <!-- These are the ISO headers to be prepended to the message types specified -->
    <header type="0200">ISO011000017</header>
    <header type="0210" ref="0200" />
    <header type="0800" ref="0200" />
    <header type="0810" ref="0200" />

    <!-- The client example uses this to create requests -->
    <template type="0800">
        <field num="1" type="BINARY" length="64">
            0000000000000000000000000000000000000000000000000000000000000000
        </field>
        <field num="7" type="DATE10">
            0000000000
        </field>
        <field num="11" type="NUMERIC" length="6">
            000000
        </field>
        <field num="15" type="DATE4">
            0000
        </field>
        <field num="70" type="NUMERIC" length="3">
            000
        </field>
    </template>

    <!-- The client example uses this to create requests -->
    <template type="0200">
        <field num="2" type="LLVAR" length="16">
            0000000000000000
        </field>
        <field num="3" type="NUMERIC" length="6">
            000000
        </field>
        <field num="4" type="NUMERIC" length="12">
            000000000000
        </field>
        <field num="7" type="DATE10">
            0000000000
        </field>
        <field num="11" type="NUMERIC" length="6">
            000000
        </field>
        <field num="12" type="TIME">
            000000000000
        </field>
        <field num="13" type="DATE4">
            0000
        </field>
        <field num="15" type="DATE4">
            0000
        </field>
        <field num="18" type="NUMERIC" length="4">
            0000
        </field>
        <field num="32" type="LLVAR" length="4">
            0000
        </field>
        <field num="37" type="ALPHA" length="12">
            ABCDEFGHIJKL
        </field>
        <field num="41" type="ALPHA" length="16">
            ABCDEFGHIJKLMNOP
        </field>
        <field num="47" type="LLVAR" length="210">
            ABCDEFGHIJKLMNOPQRSTUVWXYZ
        </field>
        <field num="48" type="LLVAR" length="210">
            ABCDEFGHIJKLMNOPQRSTUVWXYZ
        </field>
        <field num="49" type="NUMERIC" length="3">
            000
        </field>
        <field num="63" type="LLVAR" length="6">
            000000
        </field>
    </template>

    <!-- The client example uses this to read the responses -->
    <parse type="0810" extends="0800">
        <field num="39" type="NUMERIC" length="2" />
    </parse>

    <!-- The client example uses this to read the responses -->
    <parse type="0210" extends="0200">
        <field num="39" type="NUMERIC" length="2" />
    </parse>

</j8583-config>
```

Here is my test
```java
URL config = new ClassPathResource(j8583Config).getURL();

MessageFactory mfact = ConfigParser.createFromUrl(config);

mfact.setAssignDate(true);
mfact.setTraceNumberGenerator(new SimpleTraceGenerator((int) (System.currentTimeMillis() % 100000)));

String secondaryBitmap = "0000010000000000000000000000000000000000000000000000000000000000";
SimpleTraceGenerator traceNumber = new SimpleTraceGenerator((int) (System.currentTimeMillis() % 100000));
Date date = new Date();

IsoMessage echo = mfact.newMessage(0x800);
echo.setBinary(true);
echo.setValue(1, secondaryBitmap, IsoType.BINARY, 64);
echo.setValue(7, date, IsoType.DATE10, 0);
echo.setValue(11, traceNumber, IsoType.NUMERIC, 6);
echo.setValue(15, date, IsoType.DATE4, 0);
echo.setValue(70, Constants.NETWORK_ECHO, IsoType.NUMERIC, 3);

System.out.printf("TYPE: %04x\n", echo.getType());

mfact.setUseBinaryMessages(true);

System.out.println(echo.toString() + " <<< echo");
```

Here is the stacktrace:
```
java.lang.IndexOutOfBoundsException: Field index must be between 2 and 128

        at com.solab.iso8583.IsoMessage.setValue(IsoMessage.java:203)
        at com.solab.iso8583.parse.ConfigParser.parseTemplates(ConfigParser.java:189)
        at com.solab.iso8583.parse.ConfigParser.parse(ConfigParser.java:358)
        at com.solab.iso8583.parse.ConfigParser.createFromUrl(ConfigParser.java:100)
```

FYI: I'm using j8583 v1.11.0

Thankyou.

**Comment by chochos** [comment]
You're trying to set field 1. As the message in the exception says, field index must be between 2 and 128. Field 1 is the secondary bitmap and the `IsoMessage` class handles it, so don't try setting it by hand; the secondary bitmap will be added only if you have fields above 64 OR if you set the `forceSecondaryBitmap`.
