### ISSUE TITLE
Unable to parse binary bitmap

### ISSUE THREAD

**Issue by sri1790** [chochos/j8583#81]
Hi Same issue coming for me please help.

Using

```
<dependency>
    <groupId>net.sf.j8583</groupId>
    <artifactId>j8583</artifactId>
    <version>1.12.0</version>
</dependency>
```

Code:
        factory = ConfigParser.createFromClasspathConfig(properties.getId() + Constants.ISO_CONF_SUFIX);
        factory.setUseBinaryBitmap(true);
factory.parseMessage(message, 0);

Logs

2016-10-26 21:55:52.375 WARN 16584 --- [ Thread-10] com.solab.iso8583.MessageFactory : ISO8583 MessageFactory cannot parse field 101: unspecified in parsing guide
2016-10-26 21:55:52.375 WARN 16584 --- [ Thread-10] com.solab.iso8583.MessageFactory : ISO8583 MessageFactory cannot parse field 104: unspecified in parsing guide
java.text.ParseException: ISO8583 MessageFactory cannot parse fields
at com.solab.iso8583.MessageFactory.parseMessage(MessageFactory.java:449)
at com.solab.iso8583.MessageFactory.parseMessage(MessageFactory.java:298)

**Comment by sri1790** [comment]
The issue occurs due to conversation between binary to String. Now able to parse.
